### ISSUE TITLE
Icon support in control

### ISSUE THREAD

**Issue by ThorstenRollax** [ORBISAG/ORBIS.PCF.ColorfulOptionset#16]
Hi,
I like the control and the control ColofulOptionsetgrid too.
is it possible to add the icons feature in this control too?
That would be amazing.

**Comment by brasov2de** [comment]
I've thought about this too. I just need a little time. 
Given the new Virtual Components feature, I'll update the PCF  soon, and with that change I hope I'll implement the icons feature too.

**Comment by ThorstenRollax** [comment]
That sounds great, Thank you.

**Comment by brasov2de** [comment]
Hi @ThorstenRollax , 
I've just released the new version containing the icon feature... and some more.
Please have a look.

**Comment by ThorstenRollax** [comment]
Hi @brasov2de ,
the "one more thing" is cool. I like the sorting function a lot. 
Of course the integrated icons are perfect. Thank  you

**Comment by brasov2de** [comment]
Happy to hear that @ThorstenRollax ! Thanks for the feedback!
