### ISSUE TITLE
SortBy setting

### ISSUE THREAD

**Issue by renaudarmstrongvictrix** [ORBISAG/ORBIS.PCF.ColorfulOptionset#34]
Hi,
Thank you for this great component.
Unfortunatly im running into some issues wit the icon and sortby properties. 
They dont seem to be included in the solution   (20200420) but they come out as required dependencies when I try to import my solution in a target environment. Am I missing a setting up step ?
![image](https://github.com/ORBISAG/ORBIS.PCF.ColorfulOptionset/assets/91679305/17223e49-faef-47b8-b656-bec6c4648bd8)

Thank you so much for all your help

**Comment by brasov2de** [comment]
Hi  @renaudarmstrongvictrix , 
Thanks for reporting the issue. I've made a new release where the new added property is not required. Hope this solves your issue.
You can find it here: https://github.com/ORBISAG/ORBIS.PCF.ColorfulOptionset/releases/tag/v1.2
